apiVersion: v1
kind: Pod
metadata:
  name: game-2048
  labels:
    app: game-2048
spec:
  containers:
  - name: game-2048
    image: alexwhen/docker-2048
    ports:
    - containerPort: 80
