apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    app: nodeport-svc
    env: demo
spec:
  type: NodePort
  selector:
    app: nginx-demo
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80